### ISSUE TITLE
Team Building Meeting

### ISSUE THREAD

**Issue by D3XSKY** [D3XSKY/CanYouOpenIt#10]
Hold team meeting to discuss future trajectory of a project. 
Questions to discuss:

1.  Website development( technology, design, domain, hosting, &more)
2. Documentation ( who will do this including: readme, wiki)
3. Whether to go with levels( clicker hero style) or keep it simple and stupid like we wanted in the first place
4. Buttons design and implementation ( exit, options/settings, IAP?, tutorial?, statistics. &more)
5. Android licence purchase

**Comment by Anelnisam** [comment]
Dejo kompjuteru

**Comment by D3XSKY** [comment]
This meeting was held last Thursday, will create new task for the next meeting. This is in order to keep track of how many meetings we have performed.
